name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lhci:
    name: Auditar con Lighthouse
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: lhci-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM 9
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Instalar deps
        run: pnpm install --frozen-lockfile

      - name: Build (Astro) sin Ads/Analytics/SW
        run: pnpm run build
        env:
          PUBLIC_DISABLE_TRACKING: "true"

      - name: Servir build estático (gzip/brotli + caché)
        run: npx sirv-cli dist --single --host 127.0.0.1 --port 4173 --quiet --gzip --brotli --maxage 31536000 &

      - name: Esperar a que el server esté listo
        run: npx wait-on http://127.0.0.1:4173

      - name: Ejecutar Lighthouse CI
        env:
          # Evita interstitial en Chrome dentro de GitHub Runner
          LHCI_CHROME_FLAGS: "--no-sandbox --disable-dev-shm-usage --headless=new"
          # Opcional: que LHCI publique status en el PR
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx @lhci/cli autorun --upload.target=temporary-public-storage

      - name: Guardar reportes como artefacto
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lhci-reports
          path: .lighthouseci
