name: 游대 Actualizaci칩n semanal videos secundaria

on:
  schedule:
    - cron: '0 10 * * 3'  # Todos los mi칠rcoles a las 10:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v3

      - name: Instala Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instala dependencias
        run: npm install

      - name: Ejecuta el script de actualizaci칩n
        run: node src/scripts/update-experimentos-secundaria.js

      - name: Commit de los cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/data/latest-experimentos-secundaria.json
          git commit -m "游대 Video semanal actualizado (secundaria)"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
