name: Actualizar videos educativos

on:
  schedule:
    - cron: '0 7 * * 1'  # Todos los lunes a las 07:00 UTC
  workflow_dispatch:     # Permite ejecutarlo manualmente desde GitHub

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script de actualización
        run: node scripts/update-videos.js

      - name: Subir cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/data/latest-videos.json
          git commit -m "📹 Actualización semanal de videos educativos"
          git push
